apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iosr-excel-export-service
  labels:
    run: iosr-excel-export-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iosr-excel-export-service
  template:
    metadata:
      labels:
        app: iosr-excel-export-service
    spec:
      containers:
      - name: iosr-excel-export-service
        image: wachala/excel-export-service:cuber-2
        ports:
        - containerPort: 4444
          protocol: TCP
        